### ISSUE TITLE
Adding complex attribute selectors

### ISSUE THREAD

**Issue by jschneidereit** [hubbards/xpath-kotlin#5]
:wave: I'd like to write two xpaths that I believe this library doesn't support:

"get the parent of the `div` that has an id of name and a child `a` with the text 'Jim'"
```
//div[@data-id='name' and .//a[text()='Jim']]/parent::node
```

and 

"get the `div` with an id that contains some partial text"
```
//div[contains(@data-id, 'some-partial-text')]
```

I'm on 0.0.3 so perhaps I just need to upgrade 🤔

**Comment by hubbards** [comment]
I don't think your first expression matches its English description. The following XPath expression selects all parent nodes of `div`s with a `data-id` attribute equal to "name" and a child `a` with text "Jim".
```
//div[@data-id = 'name'][a/text() = 'Jim']/..
```
You can build such an expression in Kotlin with version 0.0.6 as follows
```
absolute {
  descendantOrSelf()
  child("div") {
    val l1 = relative { attribute("data-id") }
    val r1 = LiteralString("name")
    predicate(l1 equal r1)
    val l2 = relative { child("a"); child(NodeTest.Text) }
    val r2 = LiteralString("Jim")
    predicate(l2 equal r2)
  }
  parent()
}
```
Note that you must import `absolute` and `relative` from `com.github.hubbards.xpath.Path.Factory`.

You can build your second expression in Kotlin as follows
```
absolute {
  descendantOrSelf()
  child("div") {
    val args = listOf(
      relative { attribute("data-id") },
      LiteralString("some-partial-text")
    )
    predicate(FunctionCall("contains", args))
  }
}
```
I plan to introduce a factory method for this function call at some point. When I do, you can build the second expression in Kotlin as
```
absolute {
  descendantOrSelf()
  child("div") {
    val x = relative { attribute("data-id") }
    val y = LiteralString("some-partial-text")
    predicate(contains(x, y))
  }
}
```
